### ISSUE TITLE
Unix screen retaining letters/word parts from previous screen.

### ISSUE THREAD

**Issue by ghost** [Josh1147582/fallout-terminal-clone#1]
As seen below:
![screenshot from 2015-10-20 11-14-21](https://cloud.githubusercontent.com/assets/11413700/10740577/30d358c4-7be0-11e5-8b56-23dbfebd5816.png)

note: unable to test windows version

**Comment by jibby0** [comment]
Should be fixed now. I didn't handle screen refreshing properly on Linux.
