### ISSUE TITLE
Keymap variant

### ISSUE THREAD

**Issue by LenaicTerrier** [Josh1147582/fallout-terminal-clone#3]
Hi,

it would be nice to be able to use other keymaps.

```
  W
A   D
  S
```

is only valid for QWERTY keyboards.

In AZERTY (french layout) we use

```
  Z
Q   D
  S
```

An other popular layout is the one used by vim : 

```
  K
H   L
  J
```

Regards

**Comment by jibby0** [comment]
Hello,

You're absolutely right, that would be a heck of a lot easier. I'm currently working on file reading, and (hopefully) with that will come a config file of some sorts. That should allow the user to edit the keymaps. 

I originally tried to use the arrow keys, but I couldn't get ncurses or pdcurses to respond to them (just by comparing the pressed key to KEY_LEFT). If you, or anyone, has any idea why, I'd be happy to implement support for those as well.

Thank you for your recommendation!

**Comment by jibby0** [comment]
Should be resolved now, closing.
